
"""imports.py - реестр WinAPI-импортов (функция -> DLL) и CORE_IMPORTS."""

IMPORT_DLL = {

    "GetModuleHandleA":       "kernel32.dll",
    "ExitProcess":            "kernel32.dll",
    "GetLastError":           "kernel32.dll",
    "Sleep":                  "kernel32.dll",
    "GetTickCount":           "kernel32.dll",
    "GetTickCount64":         "kernel32.dll",
    "CreateFileA":            "kernel32.dll",
    "ReadFile":               "kernel32.dll",
    "WriteFile":              "kernel32.dll",
    "CloseHandle":            "kernel32.dll",
    "GetStdHandle":           "kernel32.dll",
    "Beep":                   "kernel32.dll",
    "GetFileSize":            "kernel32.dll",
    "DeleteFileA":            "kernel32.dll",
    "CopyFileA":              "kernel32.dll",
    "MoveFileA":              "kernel32.dll",
    "SetCurrentDirectoryA":   "kernel32.dll",
    "GetCurrentDirectoryA":   "kernel32.dll",
    "GetProcessHeap":         "kernel32.dll",
    "HeapAlloc":              "kernel32.dll",
    "HeapFree":               "kernel32.dll",
    "HeapReAlloc":            "kernel32.dll",
    "AddVectoredExceptionHandler": "kernel32.dll",
    "RemoveVectoredExceptionHandler": "kernel32.dll",
    "lstrlenA": "kernel32.dll",

    "RegisterClassExA":    "user32.dll",
    "CreateWindowExA":     "user32.dll",
    "LoadImageA":          "user32.dll",
    "DestroyWindow":       "user32.dll",
    "ShowWindow":          "user32.dll",
    "UpdateWindow":        "user32.dll",
    "GetMessageA":         "user32.dll",
    "TranslateMessage":    "user32.dll",
    "DispatchMessageA":    "user32.dll",
    "DefWindowProcA":      "user32.dll",
    "PostQuitMessage":     "user32.dll",
    "LoadCursorA":         "user32.dll",
    "LoadIconA":           "user32.dll",
    "GetWindowTextA":      "user32.dll",
    "SetWindowTextA":      "user32.dll",
    "SetTimer":            "user32.dll",
    "KillTimer":           "user32.dll",
    "MoveWindow":          "user32.dll",
    "GetClientRect":       "user32.dll",
    "InvalidateRect":      "user32.dll",
    "RedrawWindow":        "user32.dll",
    "SendMessageA":        "user32.dll",
    "PostMessageA":        "user32.dll",
    "GetAsyncKeyState":    "user32.dll",
    "MessageBoxA":         "user32.dll",
    "EnableWindow":        "user32.dll",
    "SetFocus":            "user32.dll",
    "GetFocus":            "user32.dll",
    "SetForegroundWindow": "user32.dll",
    "GetSystemMetrics":    "user32.dll",
    "wsprintfA":           "user32.dll",
    "FillRect":            "user32.dll",
    "GetDC":               "user32.dll",
    "ReleaseDC":           "user32.dll",
    "BeginPaint":          "user32.dll",
    "EndPaint":            "user32.dll",
    "IsWindowVisible":     "user32.dll",

    "CreateDIBSection": "gdi32.dll",
    "StretchBlt": "gdi32.dll",
    "AlphaBlend": "msimg32.dll",

    "FindResourceA": "kernel32.dll",
    "SizeofResource": "kernel32.dll",
    "LoadResource": "kernel32.dll",
    "LockResource": "kernel32.dll",
    "RtlMoveMemory": "kernel32.dll",
    "RaiseException": "kernel32.dll",

    "CreateRectRgn": "gdi32.dll",
    "CreateEllipticRgn": "gdi32.dll",
    "CreatePolygonRgn": "gdi32.dll",
    "SelectClipRgn": "gdi32.dll",
    "CombineRgn": "gdi32.dll",

    "TextOutA":               "gdi32.dll",
    "CreateSolidBrush":       "gdi32.dll",
    "DeleteObject":           "gdi32.dll",
    "SetTextColor":           "gdi32.dll",
    "SetBkMode":              "gdi32.dll",
    "SelectObject":           "gdi32.dll",
    "CreateFontA":            "gdi32.dll",
    "GetStockObject":         "gdi32.dll",
    "CreateCompatibleDC":     "gdi32.dll",
    "CreateCompatibleBitmap": "gdi32.dll",
    "BitBlt":                 "gdi32.dll",
    "DeleteDC":               "gdi32.dll",
    "Rectangle":              "gdi32.dll",
    "Ellipse":                "gdi32.dll",
    "MoveToEx": "gdi32.dll",
    "LineTo": "gdi32.dll",
    "CreatePen": "gdi32.dll",
    "SetGraphicsMode": "gdi32.dll",
    "SetWorldTransform": "gdi32.dll",
    "GetWorldTransform": "gdi32.dll",
    "Polygon": "gdi32.dll",
    "SetDIBits": "gdi32.dll",
    "PatBlt": "gdi32.dll",
    "CreateBitmap": "gdi32.dll",

    "RtlUnwind": "kernel32.dll",
    "RtlUnwindEx": "kernel32.dll",
    "__C_specific_handler": "ntdll.dll",

    "GetOpenFileNameA": "comdlg32.dll",
    "GetSaveFileNameA": "comdlg32.dll",

    "InitCommonControlsEx": "comctl32.dll",

    "OutputDebugStringA": "kernel32.dll",
}

CORE_IMPORTS = {
    "GetModuleHandleA",
    "ExitProcess",
    "RegisterClassExA",
    "CreateWindowExA",
    "ShowWindow",
    "UpdateWindow",
    "GetMessageA",
    "TranslateMessage",
    "DispatchMessageA",
    "DefWindowProcA",
    "PostQuitMessage",
    "LoadCursorA",
    "DestroyWindow",
    "SetTimer",
    "__C_specific_handler"
}

CONSOLE_CORE_IMPORTS = {
    "GetModuleHandleA",
    "ExitProcess",
    "GetStdHandle",
    "WriteFile",
    "ReadFile",
    "__C_specific_handler"
}
